# config file based/inspired by this article:
# https://blog.adam-marsden.co.uk/set-up-sass-lint-with-gulp-c7de427717ea

# aloud max 1 empty line seems not set yet ready ion sass-lint. wait for it ...
# https://github.com/sasstools/sass-lint/issues/1015

# file to check
files:
  include: "**/*.s+(a|c)ss"

  # ignore files
  ignore:
    - node_modules/**
    # here we transfrom bootstrap var (hyphens) into ours var (snake_case)
    - src/assets/stylesheets/commons/bootstrap_overwrite_var_mixins/_bootstrap_overwrite_variables.sass

options:
  formatter: stylish
  merge-default-rules: false

rules:
  bem-depth:
    - 0
    - max-depth: 1

  border-zero:
    - 1
    - convention: none

  brace-style:
    - 1
    - allow-single-line: true

  class-name-format:
    - 0
    - convention: hyphenatedbem

  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false

  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true

  extends-before-declarations: 1

  extends-before-mixins: 1

  final-newline:
    - 2
    - include: true

  force-attribute-nesting: 1

  force-element-nesting: 0

  force-pseudo-nesting: 0

  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase

  hex-length:
    - 2
    - style: long

  hex-notation:
    - 2
    - style: lowercase

  id-name-format:
    - 2
    - convention: hyphenatedbem

  indentation:
    - 2
    - size: 2

  leading-zero:
    - 0
    - include: false

  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: snakecase
      convention-explanation: Please use snake_case for variable names. No leading underscore is allowed.

  mixins-before-declarations: 0

  nesting-depth:
    - 1
    - max-depth: 3

  no-color-keywords: 2

  # TODO !!!
  no-color-literals: 1

  no-css-comments: 2

  no-debug: 2

  no-duplicate-properties: 2

  no-empty-rulesets: 2

  no-extends: 2

  no-ids: 2

  no-important: 0

  no-invalid-hex: 2

  no-mergeable-selectors: 1

  no-misspelled-properties:
    - 2
    - extra-properties: []

  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false

  no-trailing-zero: 1

  no-url-protocols: 1

  # TODO?
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []

  placeholder-in-extend: 1

  placeholder-name-format:
    - 2
    - convention: hyphenatedbem

  property-sort-order:
    - 2
    - ignore-custom-properties: false
      order: smacss

  # single quotes always
  quotes:
    - 2
    - style: single

  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4

  single-line-per-selector: 1

  space-after-bang:
    - 2
    - include: false

  space-after-colon:
    - 2
    - include: true

  space-after-comma: 0

  space-before-bang:
    - 2
    - include: true

  space-before-brace:
    - 2
    - include: true

  space-before-colon: 1

  space-between-parens:
    - 2
    - include: false

  trailing-semicolon: 1

  url-quotes: 1

  variable-for-property:
    - 0
    - properties: []

  # variable naming
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: snakecase
      convention-explanation: Please use snake_case for variable names. No leading underscore is allowed.

  zero-unit: 0
